<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>UsingZDemo</RootNamespace>
    <AssemblyName>UsingZDemo</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Clipper2ZLib\Clipper2ZLib.csproj" />
  </ItemGroup>

</Project>
