<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Clipper2.MicroBench</RootNamespace>
    <AssemblyName>Clipper2.MicroBench</AssemblyName>
    <IsPackable>false</IsPackable>
    <Optimize>true</Optimize>
    <TieredPGO>true</TieredPGO>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <NoWarn>$(NoWarn);CS0649</NoWarn>
  </PropertyGroup>

</Project>
